name: 'docker-swarm-deploy-github-action'
description: 'Deploy your Docker Swarm apps in seconds. 🚀'
inputs:
  deployment_ssh_private_key:
    description: 'The private key you have authenticated to connect to your server via SSH.'
    required: true
  remote_ssh_known_host:
    description: 'The public key of your SSH server to validate we are connecting to the right server.'
    required: true
  remote_ssh_deployment_user:
    description: 'The user that you would like to connect as on the remote server via SSH.'
    required: true
  remote_ssh_server:
    description: 'The hostname or IP address of the server you want to connect to.'
    required: true
  remote_ssh_port:
    description: 'The SSH port of the remote server you would like to connect to.'
    default: '22'
    required: false
  project_name:
    description: 'The name of the project you would like to use.'
    default: 'swarm-app'
    required: false
runs:
  using: 'composite'
  steps:
         
      - run: |
          docker -H \
            ssh://${{ inputs.remote_ssh_deployment_user }}@${{ inputs.remote_ssh_server }}:${{ inputs.remote_ssh_port }} \
            stack deploy --with-registry-auth \
            --compose-file docker-compose.yml -c docker-compose.prod.yml \
            ${{ inputs.project_name }} --prune
        shell: bash

branding:
  icon: 'zap'
  color: 'blue'
